"""Add processing_status to Upload model

Revision ID: 0c9ffc76397b
Revises: 04b9e99e4425
Create Date: 2025-05-01 23:02:48.700107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c9ffc76397b'
down_revision: Union[str, None] = '04b9e99e4425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

processing_status_enum = postgresql.ENUM('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status_enum')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    processing_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('uploads', sa.Column('processing_status', postgresql.ENUM('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='processing_status_enum'), nullable=False))
    op.create_index(op.f('uploads_processing_status_ix'), 'uploads', ['processing_status'], unique=False)
    op.drop_index('idx_vector_embeddings_embedding', table_name='vector_embeddings', postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_vector_embeddings_embedding', 'vector_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('uploads_processing_status_ix'), table_name='uploads')
    op.drop_column('uploads', 'processing_status')

    processing_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
