"""Initial database schema setup

Revision ID: 5f0e266eee9d
Revises: af5fe5a3d445
Create Date: 2025-04-30 19:25:37.744391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0e266eee9d'
down_revision: Union[str, None] = 'af5fe5a3d445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_blockmatrix_next', 'block_matrix', 'blocks', ['next_block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_blockmatrix_parent', 'block_matrix', 'blocks', ['parent_block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_blockmatrix_prev', 'block_matrix', 'blocks', ['prev_block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_document_root_block', 'documents', 'blocks', ['root_block_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_document_root_block', 'documents', type_='foreignkey')
    op.drop_constraint('fk_blockmatrix_prev', 'block_matrix', type_='foreignkey')
    op.drop_constraint('fk_blockmatrix_parent', 'block_matrix', type_='foreignkey')
    op.drop_constraint('fk_blockmatrix_next', 'block_matrix', type_='foreignkey')
    # ### end Alembic commands ###
