"""Initial database schema setup

Revision ID: e0705ec88b35
Revises: 8bbd27a4b34b
Create Date: 2025-04-29 18:18:57.020863

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0705ec88b35'
down_revision: Union[str, None] = '8bbd27a4b34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', postgresql.ENUM('DOCUMENT', 'BLOCK', 'CSV', 'PDF', name='upload_type_enum'), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=False),
    sa.Column('file_location', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('uploads_pk'))
    )
    op.create_index('ix_upload_source', 'uploads', ['source_type', 'source_identifier'], unique=False)
    op.create_index(op.f('uploads_deleted_at_ix'), 'uploads', ['deleted_at'], unique=False)
    op.create_index(op.f('uploads_source_identifier_ix'), 'uploads', ['source_identifier'], unique=False)
    op.create_index(op.f('uploads_source_type_ix'), 'uploads', ['source_type'], unique=False)
    op.create_table('vector_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', postgresql.ENUM('DOCUMENT', 'BLOCK', 'CSV_COLUMN', 'POSTGRES_COLUMN', 'PDF_CHUNK', 'USER_PROFILE', 'USER_MEMORY', 'UNKNOWN', name='embedding_source_type_enum'), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=False),
    sa.Column('related_id', sa.Text(), nullable=True),
    sa.Column('column_or_chunk_name', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vector_embeddings_pk'))
    )
    op.create_index('ix_vector_embedding_source', 'vector_embeddings', ['source_type', 'source_identifier'], unique=False)
    op.create_index(op.f('vector_embeddings_deleted_at_ix'), 'vector_embeddings', ['deleted_at'], unique=False)
    op.create_index(op.f('vector_embeddings_source_identifier_ix'), 'vector_embeddings', ['source_identifier'], unique=False)
    op.create_index(op.f('vector_embeddings_source_type_ix'), 'vector_embeddings', ['source_type'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('workspaces_pk'))
    )
    op.create_index(op.f('workspaces_deleted_at_ix'), 'workspaces', ['deleted_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('root_block_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['root_block_id'], ['blocks.id'], name='fk_document_root_block', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('documents_workspace_id_workspaces_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pk'))
    )
    op.create_index(op.f('documents_deleted_at_ix'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('documents_root_block_id_ix'), 'documents', ['root_block_id'], unique=False)
    op.create_index(op.f('documents_workspace_id_ix'), 'documents', ['workspace_id'], unique=False)
    op.create_table('workspace_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], name=op.f('workspace_uploads_upload_id_uploads_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_uploads_workspace_id_workspaces_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'upload_id', name='pk_workspace_upload')
    )
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HEADING', 'PARAGRAPH', 'LIST', 'QUOTE', 'CODE', 'EMBED', 'IMAGE', 'TABLE', 'LINE_CHART', 'BAR_CHART', 'PIE_CHART', name='blocktype_enum', native_enum=False), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('blocks_document_id_documents_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('blocks_workspace_id_workspaces_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blocks_pk'))
    )
    op.create_index(op.f('blocks_deleted_at_ix'), 'blocks', ['deleted_at'], unique=False)
    op.create_index(op.f('blocks_document_id_ix'), 'blocks', ['document_id'], unique=False)
    op.create_index(op.f('blocks_workspace_id_ix'), 'blocks', ['workspace_id'], unique=False)
    op.create_table('block_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('is_root', sa.Boolean(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('next_block_id', sa.UUID(), nullable=True),
    sa.Column('prev_block_id', sa.UUID(), nullable=True),
    sa.Column('parent_block_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], name=op.f('block_matrix_block_id_blocks_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('block_matrix_document_id_documents_fk'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['next_block_id'], ['blocks.id'], name='fk_blockmatrix_next', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['parent_block_id'], ['blocks.id'], name='fk_blockmatrix_parent', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['prev_block_id'], ['blocks.id'], name='fk_blockmatrix_prev', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('block_matrix_workspace_id_workspaces_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('block_matrix_pk')),
    sa.UniqueConstraint('document_id', 'block_id', name='uq_doc_block')
    )
    op.create_index(op.f('block_matrix_block_id_ix'), 'block_matrix', ['block_id'], unique=False)
    op.create_index(op.f('block_matrix_document_id_ix'), 'block_matrix', ['document_id'], unique=False)
    op.create_index(op.f('block_matrix_is_root_ix'), 'block_matrix', ['is_root'], unique=False)
    op.create_index(op.f('block_matrix_next_block_id_ix'), 'block_matrix', ['next_block_id'], unique=False)
    op.create_index(op.f('block_matrix_parent_block_id_ix'), 'block_matrix', ['parent_block_id'], unique=False)
    op.create_index(op.f('block_matrix_prev_block_id_ix'), 'block_matrix', ['prev_block_id'], unique=False)
    op.create_index(op.f('block_matrix_workspace_id_ix'), 'block_matrix', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('block_matrix_workspace_id_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_prev_block_id_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_parent_block_id_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_next_block_id_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_is_root_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_document_id_ix'), table_name='block_matrix')
    op.drop_index(op.f('block_matrix_block_id_ix'), table_name='block_matrix')
    op.drop_table('block_matrix')
    op.drop_index(op.f('blocks_workspace_id_ix'), table_name='blocks')
    op.drop_index(op.f('blocks_document_id_ix'), table_name='blocks')
    op.drop_index(op.f('blocks_deleted_at_ix'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('workspace_uploads')
    op.drop_index(op.f('documents_workspace_id_ix'), table_name='documents')
    op.drop_index(op.f('documents_root_block_id_ix'), table_name='documents')
    op.drop_index(op.f('documents_deleted_at_ix'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('workspaces_deleted_at_ix'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('vector_embeddings_source_type_ix'), table_name='vector_embeddings')
    op.drop_index(op.f('vector_embeddings_source_identifier_ix'), table_name='vector_embeddings')
    op.drop_index(op.f('vector_embeddings_deleted_at_ix'), table_name='vector_embeddings')
    op.drop_index('ix_vector_embedding_source', table_name='vector_embeddings')
    op.drop_table('vector_embeddings')
    op.drop_index(op.f('uploads_source_type_ix'), table_name='uploads')
    op.drop_index(op.f('uploads_source_identifier_ix'), table_name='uploads')
    op.drop_index(op.f('uploads_deleted_at_ix'), table_name='uploads')
    op.drop_index('ix_upload_source', table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###
